export const  CONVERTER_ACTION ='CONVERTER_ACTION';
export const SELECT_TO_CURRENY ='SELECT_TO_CURRENY';
export const SELECT_FROM_CURRENY ='SELECT_FROM_CURRENY';
export const AMOUNT_CURRENY ='AMOUNT_CURRENY';
export const SET_CURRENSIS ='SET_CURRENSIS';
export const CONVERT_CURRENSIS ='CONVERT_CURRENSIS';
